// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-nej62UvsueF-UUps3xFiKwLfG7vhFGk',
    appId: '1:719993274224:web:1f274d32cb62c91ffdd9b5',
    messagingSenderId: '719993274224',
    projectId: 'flutter-camping',
    authDomain: 'flutter-camping.firebaseapp.com',
    databaseURL: 'https://flutter-camping-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-camping.appspot.com',
    measurementId: 'G-1TG086SP8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMecElIr_wOb-CH3YzBnz8kYpqgYsU14',
    appId: '1:719993274224:android:68ddec949799c458fdd9b5',
    messagingSenderId: '719993274224',
    projectId: 'flutter-camping',
    databaseURL: 'https://flutter-camping-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-camping.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ2cKUZctuwsVTjPyCBY6aO4yB8mQtr4M',
    appId: '1:719993274224:ios:aea64faff163e937fdd9b5',
    messagingSenderId: '719993274224',
    projectId: 'flutter-camping',
    databaseURL: 'https://flutter-camping-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-camping.appspot.com',
    iosBundleId: 'com.example.mapSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ2cKUZctuwsVTjPyCBY6aO4yB8mQtr4M',
    appId: '1:719993274224:ios:aea64faff163e937fdd9b5',
    messagingSenderId: '719993274224',
    projectId: 'flutter-camping',
    databaseURL: 'https://flutter-camping-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-camping.appspot.com',
    iosBundleId: 'com.example.mapSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-nej62UvsueF-UUps3xFiKwLfG7vhFGk',
    appId: '1:719993274224:web:b0dee8959fde7dfefdd9b5',
    messagingSenderId: '719993274224',
    projectId: 'flutter-camping',
    authDomain: 'flutter-camping.firebaseapp.com',
    databaseURL: 'https://flutter-camping-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-camping.appspot.com',
    measurementId: 'G-E9EVMQKLQ2',
  );
}
